// Package generate 는 Manifest 를 독립 CLI 의 Go 소스로 물질화한다.
//
// 런타임 인터프리터(internal/cli)가 매니페스트를 *읽어서* 명령을 만든다면,
// 여기서는 같은 매니페스트를 *적어서* 코드로 만든다. 다만 실행 자체는 양쪽 모두
// clirun.Run 하나를 부르므로 두 CLI 의 동작이 갈릴 수 없다.
//
// 생성물이 import 하는 것은 clirun 뿐이다 — internal/ 은 남의 모듈에서 못 쓴다.
package generate

import (
	"bytes"
	_ "embed"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/Kwangseok-Seo/cli-maker/internal/manifest"
)

// 템플릿을 문자열 리터럴로 코드에 박지 않고 파일로 두면, gofmt·에디터·diff 가
// 그 내용에 닿는다. embed 가 빌드 시점에 바이너리 안으로 넣어 주므로 실행할 때
// 파일을 찾지 않는다.
//
//go:embed main.go.tmpl
var mainTmplText string

//go:embed go.mod.tmpl
var goModTmplText string

// 파싱은 시작할 때 한 번. 여기서 실패하면 유저 입력 문제가 아니라 우리 템플릿의
// 버그이므로 Must 로 즉시 죽는 편이 낫다.
var (
	mainTmpl  = template.Must(template.New("main.go").Parse(mainTmplText))
	goModTmpl = template.Must(template.New("go.mod").Parse(goModTmplText))
)

// GeneratedHeader 는 생성물의 첫 줄이다. main.go.tmpl 의 첫 줄과 같아야 하며,
// 그 사실은 테스트가 지킨다. 덮어써도 되는 파일인지 가릴 때 이 표식을 본다.
const GeneratedHeader = "// Code generated by cli-maker. DO NOT EDIT."

// goVersion 은 생성될 go.mod 의 go 줄이다.
//
// 우리 go.mod 와 같은 값을 한 번 더 적은 것이다. 자동 추론 대신 눈에 보이는 상수로
// 둔 이유는, 이 값이 1.22 아래로 내려가면 for 루프 변수의 의미가 바뀌어 생성물이
// 조용히 달라지기 때문이다 — 조용히 변할 수 있는 자리는 눈에 보여야 한다.
const goVersion = "1.26"

// data 는 main.go 템플릿에 넘기는 단 하나의 값이다.
//
// 템플릿은 인자를 하나만 받으므로, 매니페스트에 부가 정보를 얹으려면 감싸야 한다.
// 임베딩해 두면 .Name·.Commands 가 승격돼 템플릿에서 그대로 보이고, 얹은 것만
// 필드로 추가된다.
type data struct {
	*manifest.Manifest
	Source string
}

// Main 은 m 으로부터 독립 CLI 의 main.go 소스를 w 에 쓴다.
// source 는 생성물 머리말에 남길 원본 매니페스트 경로다.
//
// 템플릿은 텍스트만 만들 뿐 Go 문법을 모르므로, 낸 것이 정말 Go 인지 파서에게
// 물어본 뒤에야 w 로 보낸다. 검산에 걸리면 w 에는 한 바이트도 쓰지 않는다 —
// 리다이렉트된 파일이 반쯤 깨진 채로 남는 것이 조용한 실패이기 때문이다.
func Main(w io.Writer, m *manifest.Manifest, source string) error {
	var buf bytes.Buffer
	if err := mainTmpl.Execute(&buf, data{Manifest: m, Source: source}); err != nil {
		return err
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("생성된 소스가 올바른 Go 가 아니다 (템플릿 결함): %w", err)
	}

	_, err = w.Write(src)
	return err
}

// GoMod 는 생성물의 go.mod 를 w 에 쓴다.
//
// require 줄은 적지 않는다. 실제 import 를 보고 채우는 것은 go mod tidy 가 더
// 정확하고, 우리가 버전을 지어내면 그게 곧 거짓이 된다. 특히 cli-maker 자신은
// 아직 배포되지 않아 어떤 버전을 적어도 받아올 수 없다.
func GoMod(w io.Writer, module string) error {
	return goModTmpl.Execute(w, struct{ Module, GoVersion string }{module, goVersion})
}

// Module 은 dir 에 main.go 와 go.mod 를 써서 빌드 가능한 모듈 한 벌을 만든다.
//
// 이미 있는 파일을 함부로 덮지 않는다. main.go 는 우리가 만든 표식이 있을 때만
// 덮어쓰고, go.mod 는 tidy 가 채운 뒤부터 유저의 것이므로 있으면 그대로 둔다.
// 남겨 둔 경우 kept 에 그 경로를 담아 돌려준다 — 알리는 것은 호출자의 몫이다.
func Module(dir string, m *manifest.Manifest, source, module string) (kept []string, err error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}

	mainPath := filepath.Join(dir, "main.go")
	if err := checkOverwritable(mainPath); err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := Main(&buf, m, source); err != nil {
		return nil, err
	}
	if err := os.WriteFile(mainPath, buf.Bytes(), 0o644); err != nil {
		return nil, err
	}

	modPath := filepath.Join(dir, "go.mod")
	if _, err := os.Stat(modPath); err == nil {
		return []string{modPath}, nil
	}

	buf.Reset()
	if err := GoMod(&buf, module); err != nil {
		return nil, err
	}
	return nil, os.WriteFile(modPath, buf.Bytes(), 0o644)
}

// checkOverwritable 은 path 가 없거나, 우리가 만든 파일일 때만 통과시킨다.
// 유저가 직접 쓴 main.go 를 말없이 지우는 것이 이 명령의 가장 큰 위험이다.
func checkOverwritable(path string) error {
	f, err := os.Open(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	defer f.Close()

	head := make([]byte, len(GeneratedHeader))
	n, _ := io.ReadFull(f, head)
	if strings.HasPrefix(string(head[:n]), GeneratedHeader) {
		return nil
	}
	return fmt.Errorf("%s 는 cli-maker 가 만든 파일이 아니다 — 덮어쓰지 않았다", path)
}
